version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - orwa_network

  # Strapi Backend
  mm-strapi:
    build:
      context: .
      dockerfile: Dockerfile.mm-strapi
    restart: unless-stopped
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: false
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: key1,key2,key3,key4
      ADMIN_JWT_SECRET: admin-jwt-secret-dev
      API_TOKEN_SALT: api-token-salt-dev
      TRANSFER_TOKEN_SALT: transfer-token-salt-dev
      JWT_SECRET: jwt-secret-dev
    ports:
      - "1337:1337"
    depends_on:
      - mysql
    networks:
      - orwa_network

  # Frontend Applications
  grant-application:
    build:
      context: .
      dockerfile: Dockerfile.grant-application
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - mm-strapi
    networks:
      - orwa_network

  membership-application:
    build:
      context: .
      dockerfile: Dockerfile.membership-application
    restart: unless-stopped
    ports:
      - "4201:80"
    depends_on:
      - mm-strapi
    networks:
      - orwa_network

  conference-registration:
    build:
      context: .
      dockerfile: Dockerfile.conference-registration
    restart: unless-stopped
    ports:
      - "4202:80"
    depends_on:
      - mm-strapi
    networks:
      - orwa_network

  grant-map:
    build:
      context: .
      dockerfile: Dockerfile.grant-map
    restart: unless-stopped
    ports:
      - "4203:80"
    depends_on:
      - mm-strapi
    networks:
      - orwa_network

  grant-scoring:
    build:
      context: .
      dockerfile: Dockerfile.grant-scoring
    restart: unless-stopped
    ports:
      - "4204:80"
    depends_on:
      - mm-strapi
    networks:
      - orwa_network

  associate-directory:
    build:
      context: .
      dockerfile: Dockerfile.associate-directory
    restart: unless-stopped
    ports:
      - "4205:80"
    depends_on:
      - mm-strapi
    networks:
      - orwa_network

volumes:
  mysql_data:

networks:
  orwa_network:
    driver: bridge