import { StrapiFormattedFile } from "../types";
import { AssociateMembershipPayload, EmptyAssociateMembershipPayload } from "../types/AssociateMembership";

export const associateTestPayload: AssociateMembershipPayload = {
    associate: "",
    name: "John Doe Associates",
    category: "Accountant",
    member_level: "Gold",
    website: "https://www.johndoeassociates.com",
    logo: [],
    phone: "123-456-7890",
    total_years: 5,
    email: "info@johndoeassociates.com",
    contact_primary: {
        first : "John",
        last : "Doe",
      email: "john.doe@example.com",
      phone: "123-456-7890",
      title: "CEO",
    },
    contact_secondary: {
        first : "Sarah",
        last : "Johnson",
      email: "sarah.johnson@example.com",
      phone: "987-654-3210",
        title: "COO",
    },
    address_street: "123 Main St",
    address_city: "Anytown",
    address_state: "Texas",
    address_zip: "12345",
    mailing_address_city: "Anytown",
    mailing_address_state: "Texas",
    mailing_address_street: "123 Main St",
    mailing_address_zip: "12345",
    membership_directory_type: "None",
    // payment_last_date: "2024-09-15",
    payment_method: "Card",
    payment_amount: 250.0,
    fee_membership: 200.0,
    fee_scholarship: 25.0,
    payment_details: "Paid in full via card",
    // wp_uid: 123456,
    // wp_eid: 789012,
    application_date: "2024-09-10",
    // directory_mailed: true,
    primary_ad: null as unknown as StrapiFormattedFile,
    // payment_previous_date: "2023-09-15",
    directory_sent_date: "2024-09-20",
    membership: -1,
    address_billing_line1: "123 Water St.",
    address_billing_city: "Clearwater",
    address_billing_state: "Oklahoma",
    address_billing_zip: "73020",
    billing_email: "marcosje2005@gmail.com",
    billing_phone: "555-123-4567",
    billing_first_name: "john",
    billing_last_name: "doe",
    payment_information: {
      card: "4111111111111111",
      exp: "12/23",
      cvv: "123",
    },
  };

export const emptyAssociatePayload: EmptyAssociateMembershipPayload = {
    associate: "",
    name: "",
    category: "",
    logo: [],
    phone: "",
    total_years: 0,
    email: "",
    contact_primary: {
        first : "",
        last : "",
      email: "",
      phone: "",
      title: "",
    },
    contact_secondary: {
        first : "",
        last : "",
      email: "",
      phone: "",
        title: "",
    },
    address_street: "",
    address_city: "",
    address_state: "",
    address_zip: "",
    mailing_address_city: null,
    mailing_address_state: null,
    mailing_address_street: null,
    mailing_address_zip: null,
    membership_directory_type: "",
    payment_method: "",
    payment_amount: 0,
    fee_membership: 0,
    fee_scholarship: 0,
    payment_details: "",
    primary_ad: null as unknown as StrapiFormattedFile,
    membership: 0,
    address_billing_line1: "",
    address_billing_city: "",
    address_billing_state: "",
    address_billing_zip: "",
    billing_email: "",
    billing_phone: "",
    billing_first_name: "",
    billing_last_name: "",
    payment_information: {
      card: "",
      exp: "",
      cvv: "",
    },

}

  