import {
  county,
  EmptyWatersystemPayload,
  WatersystemMembershipPayload,
} from "../types/WatersystemMebership";
import { emptyDirectoryContactRow } from "../watersystem-steps/DirectoryContactsStep";

export const watersystemPayload: WatersystemMembershipPayload = {
  watersystem: "",
  name: "City of Ardmore",
  office_hours: "7:30 -  4:30",
  meters: 12000,
  url: "ardmorecity.org",
  board_meeting: "Commission Meeting",
  funding: false,
  soonerwarn: false,
  county: "Carter",
  total_years: 0,
  member_type: "TN",
  system_type_dirty: ["Sur", "Sew"],
  email: "sgeurin@ardmorecity.org",
  phone: "(580) 221-5402",
  fax: "580-221-5419",
  address_mailing_pobox: "P.O. Box 249",
  address_mailing_city: "Ardmore",
  address_mailing_state: "Oklahoma",
  address_mailing_zip: "73402",
  address_physical_line1: "317 Veterans",
  address_physical_line2: "",
  address_physical_city: "Ardmore",
  address_physical_state: "Oklahoma",
  address_physical_zip: "73401",
  membership_directory_type: "Both",
  payment_last_date: null,
  payment_method: "Card",
  payment_amount: 0,
  fee_scholarship: 0,
  fee_connections: 4000,
  fee_membership: 90,
  payment_details: "",
  legal_entity_name: "City of Ardmore",
  address_billing_line1: "City of Ardmore",
  address_billing_city: "Ardmore",
  address_billing_state: "Oklahoma",
  address_billing_zip: "73402",
  billing_email: "sgeurin@ardmorecity.org",
  billing_phone: "(580) 221-5402",
  billing_first_name: "Shawn",
  billing_last_name: "Geurin",
  payment_information: null,
  contacts: [emptyDirectoryContactRow()],
};

export const emptyWatersystemPayload: EmptyWatersystemPayload = {
  watersystem: "",
  name: "",
  region: null,
  office_hours: "",
  meters: 0,
  url: "",
  board_meeting: "",
  funding: false,
  soonerwarn: false,
  county: "" as county,
  total_years: 0,
  member_type: "",
  system_type_dirty: [],
  email: "",
  phone: "",
  fax: "",
  address_mailing_pobox: "",
  address_mailing_city: "",
  address_mailing_state: "",
  address_mailing_zip: "",
  address_physical_line1: "",
  address_physical_line2: "",
  address_physical_city: "",
  address_physical_state: "",
  address_physical_zip: "",
  membership_directory_type: "",
  payment_last_date: null,
  payment_method: "",
  payment_amount: 0,
  fee_connections: 0,
  fee_membership: 0,
  fee_scholarship: 0,
  payment_details: "",
  legal_entity_name: "",
  address_billing_line1: "",
  address_billing_city: "",
  address_billing_state: "",
  address_billing_zip: "",
  billing_email: "",
  billing_phone: "",
  billing_first_name: "",
  billing_last_name: "",
  payment_information: {
    card: "",
    exp: "",
    cvv: "",
  },
  contacts: [emptyDirectoryContactRow()],
};
