import { IContactPayload, IGrantApplicationFormPayload, StrapiFormattedFile } from "../types/types";

export const defaultPayload = {
      additional_funding_requested: 0,
      lrsp_plan: false,
      more_info_lrsp: false,
      legal_entity_name: "",
      facility_id: "",
      original_application_number: "",
      county: "",
      physical_address_street: "",
      physical_address_line_two: "",
      physical_address_city: "",
      physical_address_state: "Oklahoma",
      physical_address_zip: "",
      physical_same_as_mailing: false,
      mailing_address_street: "",
      mailing_address_line_two: "",
      mailing_address_city: "",
      mailing_address_state: "Oklahoma",
      mailing_address_zip: "",
      point_of_contact: {} as IContactPayload,
      chairman: {
        first: "",
        last: "",
        email: "",
        phone: "",
        title: 'Chairman',
      } as IContactPayload,
      chairman_also_mayer_of_municipal_city: false,
      has_engineer: false,
      engineer: {
        first: "",
        last: "",
        email: "",
        phone: "",
        title: 'Engineer',
      } as IContactPayload,
      drinking_or_wastewater: "Drinking Water",
      // drinking_water_projects_selected: "",
      // wastewater_projects_selected: "",
      other_describe: "",
      description_justification_estimated_cost: "",
      // project_proposal_birds: [],
      combined_cost_of_projects: 0,
      // requested_grant_amount: "",
      // portion_matched_by_recipient: "",
      // minimum_utility_financial_contribution: "",
      engineering_report: "No",
      report_approved_by_deq: "No",
      resolves_violation: "No",
      // notice_of_violation: [],
      signatory_name: "",
      signatory_title: "",
      signature: "",
      other_needs: "",
      grant: 4,
      application_date: new Date(),
      status: 12,
      selected_projects: [],
      // approved_projects: [] ,
      change_order_request: "No",
      proposals: [] as StrapiFormattedFile[],
      uploaded_engineering_report: [],
      uploaded_notice_of_violation: [],
      satisfy_deq_issued_order: false,
      engineering_report_deq_approved: "No",
      uploaded_additional_files: [],
      consent_order_number: "", // Add this property
      money_set_aside: false, // Change type to boolean
      applied_to_other_loans: false, // Change type to boolean
      consent_order: {} as StrapiFormattedFile,
      population_served: 0, 
      requested_grant_amount: 0, 
      additional_information: "",
    } as IGrantApplicationFormPayload;