

export const guestRole: any = {
  "Guest": [
    { action: "read", resource: "watersystems" },
    { action: "read", resource: "assets" },
    { action: "read", resource: "staff" },
    { action: "read", resource: "contacts" },
    { action: "read", resource: "users" },
    { action: "read", resource: "associates" },
    { action: "read", resource: "membership-items" },
    { action: "read", resource: "memberships" },
    { action: "read", resource: "invoices" },
    { action: "read", resource: "training-events" },
    { action: "read", resource: "training-event-logs" },
    { action: "read", resource: "training-event-registrations" },
    { action: "read", resource: "training-instructors" },
    { action: "read", resource: "training-topics" },
    { action: "read", resource: "training-settings" },
    { action: "read", resource: "training-instructor-certifications" },
    { action: "read", resource: "conference-attendees" },
    { action: "read", resource: "conference-extras" },
    { action: "read", resource: "conference-sponsorships" },
    { action: "read", resource: "conference-sponsors" },
    { action: "read", resource: "conference-tickets" },
    { action: "read", resource: "conference-booths" },
    { action: "read", resource: "conference-contestants" },
    { action: "read", resource: "conference-registrations" },
    { action: "read", resource: "conference-schedules" },
    { action: "read", resource: "conferences" },
    { action: "read", resource: "grants" },
    { action: "read", resource: "grant-application-finals" },
    { action: "read", resource: "grant-payouts" },
    { action: "read", resource: "grant-statuses" },
    { action: "read", resource: "grant-sub-statuses" },
    { action: "read", resource: "activities" },
    { action: "read", resource: "activity-relations" },
    { action: "read", resource: "upload/files" },
    { action: "read", resource: "shared.field-metas" },
    { action: "read", resource: "components_shared_field_metas" },
    { action: "read", resource: "upload" },
  ],
};