// Define the shape of our configuration
export interface AppConfig {
    VITE_API_URL: string
    VITE_ASSET_API_URL: string
    VITE_AUTHENTIK_CLIENT_ID: string
    VITE_AUTHENTIK_AUTH_URL: string
    VITE_AUTHENTIK_TOKEN_URL: string
    VITE_REDIRECT_URI: string
    VITE_AUTHENTIK_LOGOUT_URL: string
    VITE_AUTHENTIK_CLIENT_SECRET: string
    VITE_GOOGLE_MAPS_API_KEY: string
}

// Extend the Window interface to include APP_CONFIG
declare global {
    interface Window {
        APP_CONFIG: AppConfig
    }
}

// Helper to get environment variables with fallback
const getEnvVar = (key: keyof AppConfig): string => {
    // In development, use Vite's import.meta.env
    if (import.meta.env.DEV) {
        const value = import.meta.env[key]
        if (!value) {
            console.warn(`Missing development environment variable: ${key}`)
        }
        return value || ''
    }
    
    // In production, use window.APP_CONFIG (generated by docker-entrypoint.sh)
    if (typeof window !== 'undefined' && window.APP_CONFIG) {   
        const value = window.APP_CONFIG[key]
        if (!value) {
            console.warn(`Missing runtime config: ${key}`)
        }
        return value || ''
    }

    console.error('Configuration not available - ensure config.js is loaded')
    return ''
}

// Export a configuration object that works in both environments
export const config: AppConfig = {
    VITE_API_URL: getEnvVar('VITE_API_URL'),
    VITE_ASSET_API_URL: getEnvVar('VITE_ASSET_API_URL'),
    VITE_AUTHENTIK_CLIENT_ID: getEnvVar('VITE_AUTHENTIK_CLIENT_ID'),
    VITE_AUTHENTIK_AUTH_URL: getEnvVar('VITE_AUTHENTIK_AUTH_URL'),
    VITE_AUTHENTIK_TOKEN_URL: getEnvVar('VITE_AUTHENTIK_TOKEN_URL'),
    VITE_AUTHENTIK_LOGOUT_URL: getEnvVar('VITE_AUTHENTIK_LOGOUT_URL'),
    VITE_AUTHENTIK_CLIENT_SECRET: getEnvVar('VITE_AUTHENTIK_CLIENT_SECRET'),
    VITE_GOOGLE_MAPS_API_KEY: getEnvVar('VITE_GOOGLE_MAPS_API_KEY'),
    VITE_REDIRECT_URI: getEnvVar('VITE_REDIRECT_URI'),
}

// Export a function to get fresh config (useful for components that need reactive config)
export const getConfig = (): AppConfig => {
    if (import.meta.env.DEV) {
        // In development, always return fresh values from import.meta.env
        return {
            VITE_API_URL: import.meta.env.VITE_API_URL || '',
            VITE_ASSET_API_URL: import.meta.env.VITE_ASSET_API_URL || '',
            VITE_AUTHENTIK_CLIENT_ID: import.meta.env.VITE_AUTHENTIK_CLIENT_ID || '',
            VITE_AUTHENTIK_AUTH_URL: import.meta.env.VITE_AUTHENTIK_AUTH_URL || '',
            VITE_AUTHENTIK_TOKEN_URL: import.meta.env.VITE_AUTHENTIK_TOKEN_URL || '',
            VITE_REDIRECT_URI: import.meta.env.VITE_REDIRECT_URI || '',
            VITE_AUTHENTIK_LOGOUT_URL: import.meta.env.VITE_AUTHENTIK_LOGOUT_URL || '',
            VITE_GOOGLE_MAPS_API_KEY: import.meta.env.VITE_GOOGLE_MAPS_API_KEY || '',
            VITE_AUTHENTIK_CLIENT_SECRET: import.meta.env.VITE_AUTHENTIK_CLIENT_SECRET || '',
        }
    }
    
    // In production, use window.APP_CONFIG
    if (typeof window !== 'undefined' && window.APP_CONFIG) {
        return window.APP_CONFIG
    }

    throw new Error('Configuration not available - ensure config.js is loaded before the application starts')
} 