import { IScholarshipApplicationPayload } from "../types/types";

export const scholarshipDefaultPayload: IScholarshipApplicationPayload = {
  applicant_first_name: "",
  applicant_middle_name: "",
  applicant_last_name: "",
  applicant_phone: "",
  applicant_email: "",
  applicant_street: "",
  applicant_city: "",
  applicant_state: "Oklahoma",
  applicant_zip: "",

  system_name: "",
  watersystem: null,
  relationship: "",
  eligible_participant_name: { first: "", last: "" },
  eligible_participant_title: "",
  eligible_participant_phone: "",
  eligible_participant_email: "",
  eligible_participant_address: {
    street: "",
    city: "",
    state: "Oklahoma",
    zip: "",
  },

  school_name: "",
  graduation_date: "",
  school_address: {
    street: "",
    city: "",
    state: "Oklahoma",
    zip: "",
  },
  gpa: "",
  sat_score: "",
  act_score: "",
  transcript: null,
  test_scores: null,

  first_year: "",
  credits_completed: "",
  credits_required: "",
  college_gpa: "",
  education_type: "",
  major: "",
  awards: "",

  recommender1_name: { first: "", last: "" },
  recommender1_email: "",
  recommender1_phone: "",
  recommendation_letter_1: null,
  recommender2_name: { first: "", last: "" },
  recommender2_email: "",
  recommender2_phone: "",
  recommendation_letter_2: null,

  financial_resources: [{ institution: "", amount: "" }],

  essay: null,
  biography: null,
  photograph: null,
  applicant_pdf: null,

  age_confirm: "",
  applicant_certification: false,
  applicant_certification_date: "",
  guardian_name: { first: "", last: "" },
  guardian_certification: false,
  guardian_certification_date: "",
};
